require 'fileutils'
require 'bundler'

task :create_test_app do
  FileUtils.rm_rf('test_app') if Dir.exist?('test_app')
  system('ruby -- ../isomorfeus/bin/isomorfeus test_app -m policy -s test_app_files')
end

task :specs => :create_test_app do
  puts <<~ASCII
   _                         ___                          ___
  (_)__ ___  __ _  ___  ____/ _/__ __ ____________  ___  / (_)_____ __
 / (_-</ _ \/  ' \/ _ \/ __/ _/ -_) // (_-<___/ _ \/ _ \/ / / __/ // /
/_/___/\___/_/_/_/\___/_/ /_/ \__/\_,_/___/  / .__/\___/_/_/\__/\_, /
                                            /_/                /___/
  ASCII
  pwd = Dir.pwd
  Dir.chdir('test_app')
  Bundler.with_original_env do
    system('bundle exec rspec')
  end
  Dir.chdir(pwd)
  FileUtils.rm_rf('test_app')
end

task :start_test_app => :create_test_app do
  pwd = Dir.pwd
  Dir.chdir('test_app')
  Bundler.with_original_env do
    system('bundle exec iodine')
  end
  Dir.chdir(pwd)
end

task default: :specs
