require 'fileutils'
require 'bundler'
require 'bundler/cli'
require 'bundler/cli/exec'

task :specs do
  puts <<~'ASCII'
   _                         ___
  (_)__ ___  __ _  ___  ____/ _/__ __ _____
 / (_-</ _ \/  ' \/ _ \/ __/ _/ -_) // (_-<
/_/___/\___/_/_/_/\___/_/ /_/ \__/\_,_/___/

  ASCII
  pwd = Dir.pwd
  system('bundle update')
  options = { keep_file_descriptors: false }
  options.define_singleton_method(:keep_file_descriptors?) do
    false
  end
  if Gem.win_platform?
    system('bundle exec rspec')
  else
    pid = fork do
      Bundler::CLI::Exec.new(options, ['rspec']).run
    end
    Process.waitpid(pid)
  end
  Dir.chdir(pwd)
end

task default: :specs
