require 'fileutils'
require 'bundler'

task :create_test_app do
  FileUtils.rm_rf('test_app') if Dir.exist?('test_app')
  system('ruby -- ../isomorfeus/bin/isomorfeus test_app -m mailer -s test_app_files')
end

task :html2text_specs do
  Bundler.with_original_env do
    system('bundle exec rspec')
  end
end

task :mailer_specs => [:create_test_app] do
  puts <<~'ASCII'
   _                         ___                           _ __
  (_)__ ___  __ _  ___  ____/ _/__ __ ___________ _  ___ _(_) /__ ____
 / (_-</ _ \/  ' \/ _ \/ __/ _/ -_) // (_-<___/  ' \/ _ `/ / / -_) __/
/_/___/\___/_/_/_/\___/_/ /_/ \__/\_,_/___/  /_/_/_/\_,_/_/_/\__/_/

  ASCII
  pwd = Dir.pwd
  Dir.chdir('test_app')
  Bundler.with_original_env do
    system('bundle exec rspec')
  end
  Dir.chdir(pwd)
  FileUtils.rm_rf('test_app')
end

task :start_test_app => :create_test_app do
  pwd = Dir.pwd
  Dir.chdir('test_app')
  Bundler.with_original_env do
    system('bundle exec iodine')
  end
  Dir.chdir(pwd)
end

task specs: [:mailer_specs, :html2text_specs]

task default: :specs
