require 'fileutils'
require 'bundler'
require 'cowsay'

task :create_test_app do
  FileUtils.rm_rf('test_app') if Dir.exist?('test_app')
  system('ruby -- ../isomorfeus/bin/isomorfeus test_app -m mailer -s test_app_files')
end

task :html2text_specs do
  Bundler.with_original_env do
    system('bundle exec rspec')
  end
end

task :specs => [:html2text_specs, :create_test_app] do
  puts Cowsay.say "Testing #{File.dirname(__FILE__).split('/').last.upcase}. NO chance for bugs!", "Ghostbusters"
  pwd = Dir.pwd
  Dir.chdir('test_app')
  Bundler.with_original_env do
    system('bundle exec rspec')
  end
  Dir.chdir(pwd)
  FileUtils.rm_rf('test_app')
end

task :start_test_app => :create_test_app do
  pwd = Dir.pwd
  Dir.chdir('test_app')
  Bundler.with_original_env do
    system('bundle exec iodine')
  end
  Dir.chdir(pwd)
end

task default: :specs
